<?php

namespace App\Classes\Constants;

class ListeningTest
{
    const LISTENING_PART_1 = [
        1 => 'Hearing',
        2 => 'Composition',
        3 => 'Grows',
        4 => 'Present',
        5 => 'Dennis',
        6 => 'Size',
        7 => 'Founded',
        8 => 'My Own',
        9 => 'Loathed',
        10 => 'Shes',
        11 => 'Chess',
        12 => '40P',
        13 => 'No.6',
        14 => 'Horrid Day',
        15 => 'Joys',
        16 => 'Can',
        17 => 'Some Kinds',
        18 => 'Tearful',
        19 => 'Regain',
        20 => 'Steve',
        21 => 'Why',
        22 => 'Reading',
        23 => 'Glass',
        24 => 'Deprived',
        25 => 'Can See',
        26 => 'Pictures',
        27 => 'Wouldnt',
        28 => 'Blended',
        29 => 'Notice',
        30 => 'Collected',
        31 => 'Indian',
        32 => 'Washing',
        33 => 'Rarely',
        34 => 'Glass',
        35 => 'Lash',
        36 => 'Talk',
        37 => 'Text',
        38 => 'Hatch',
        39 => 'Pennys',
        40 => 'Two Minibuses',
        41 => 'Buyable',
        42 => 'Board School',
        43 => 'I Reckon',
        44 => 'Shod',
        45 => 'Sealing Tape',
        46 => 'Persecution',
        47 => 'Menial',
        48 => 'Committee',
        49 => 'View',
        50 => 'Slot',
    ];

    const LISTENING_PART_2 = [
        51 => 'Chaired',
        52 => 'Delicate',
        53 => 'Riding',
        54 => 'Whose Darts',
        55 => 'Fiscal',
        56 => 'Tight',
        57 => 'Set',
        58 => 'Mass Of',
        59 => 'Context',
        60 => 'Gods',
        61 => 'Unexceptionable',
        62 => 'Clouds',
        63 => 'Belly',
        64 => 'Dry',
        65 => 'Cabin Up',
        66 => 'Stocks',
        67 => 'Bison',
        68 => 'Launch',
        69 => 'Finnish',
        70 => 'Trials',
        71 => 'Ash',
        72 => 'Ill',
        73 => 'Old',
        74 => 'Euston',
        75 => 'Crude',
        76 => 'Barrel',
        77 => 'Arrival',
        78 => 'Inventory',
        79 => 'Newer System',
        80 => 'J&B',
        81 => 'Ha',
        82 => 'Hair-Dryers',
        83 => 'Women',
        84 => 'Free',
        85 => 'Bath Day',
        86 => 'Autistic',
        87 => 'Scarred',
        88 => 'Oarsman Rowed',
        89 => 'Eternal',
        90 => 'Andean',
        91 => 'Rod',
        92 => 'Personnel',
        93 => 'He And',
        94 => 'Loyal',
        95 => 'Freak',
        96 => 'Precedent',
        97 => 'Terrain',
        98 => 'To Date',
        99 => 'Obese!',
        100 => 'Pirated'
    ];

}
